import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import java.text.ParseException;

import logica.Asesor;
import logica.Cliente;
import logica.Controlador;
import logica.Piso;

import org.junit.Before;
import org.junit.Test;

import presentacion.CrearPisoJDialog;
import excepciones.LogicaExcepcion;

/**
 * @author Fran Martí
 */

public class CrearPisoJDialogTest_Bug532 {
	String supTotal;
	int superficie;
	Controlador controlador;
	CrearPisoJDialog piso;
	Cliente cliente;
	Asesor asesor;
	Piso pi;
	
	 @Before
	    public void inicializar() {
		 	controlador = Controlador.dameControlador();
		 	supTotal = "200";
		 	
		 	cliente = new Cliente("12345678A", "Antonio", "Manostijeras");
            asesor = new Asesor("0001", "Paquito");
            
            pi = new Piso("12","calle","localidaddd", "1/1/2311", supTotal, "V", "2", asesor,cliente);
		 	
		 	//piso = new CrearPisoJDialog(controlador);
		 	//piso.setSuperficie(supTotal);
	    }

	@Test
	public void testCrearPisoJDialog() {
		
		try{
	    	//piso.botonCrear();
			controlador.crearPiso(pi);
	    	fail("El método debería de haber fallado");
    	}
    	catch(LogicaExcepcion e){
    		assertTrue(true);
    	}
		/*try{
			superficie = Integer.parseInt(piso.getSuperficie_total());
			assertTrue("El número no es positivo", superficie>=0);
		}
		catch(NumberFormatException e){
			fail("Debes de introducir un valor numérico");
		}*/
		
	}

}
