import static org.junit.Assert.*;
import logica.Controlador;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import persistencia.ConnectionManager;
import presentacion.CrearNaveIndustrial;
import excepciones.DAOExcepcion;
import excepciones.LogicaExcepcion;


/**
 * @author Fran Martí
 */

public class CrearNaveIndustrialTest_Bug564 {
	
    String numPuertas;
    int numPu;
    CrearNaveIndustrial nave;
    Controlador controlador;
    
    
    
    @Before
    public void inicializar() {
    	numPuertas = "asd";
    	controlador = Controlador.dameControlador();
    	
    	nave = new CrearNaveIndustrial(controlador);
    	nave.setCampos(numPuertas);
    	nave.getContentPane().setVisible(false);
    }

	@Test
	public void testCrearNaveIndustrial() {
		
		try{
			nave.boton();
	    	fail("El método debería de haber fallado");
    	}
    	catch(LogicaExcepcion e){
    		assertTrue(true);
    	}
		/*
		try{
			numPu = Integer.parseInt(nave.getNum_puertas());
			assertTrue("El número no es positivo", numPu>=0);
		}
		catch(NumberFormatException e){
			fail("Debes de introducir un valor numérico");
		}*/
	}
	
	@After
    public void after(){
    	try{
    		ConnectionManager connManager = new ConnectionManager("practicaFinal");
            connManager.connect();
            
            connManager.updateDB("delete from NAVEINDUSTRIAL where num_puertas='" + numPuertas + "'");
            
            connManager.close();
    	}
    	catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        }
    	
    	catch(DAOExcepcion ex){
    		ex.printStackTrace();    		
    	}
    }

}
