import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import java.text.ParseException;

import logica.Controlador;

import org.junit.Before;
import org.junit.Test;

import presentacion.CrearPisoJDialog;
import excepciones.LogicaExcepcion;

/**
 * @author Fran Martí
 */

public class CrearPisoJDialogTest_Bug532 {
	String supTotal;
	int superficie;
	Controlador controlador;
	CrearPisoJDialog piso;
	
	 @Before
	    public void inicializar() {
		 	controlador = Controlador.dameControlador();
		 	supTotal = "200";
		 	
		 	piso = new CrearPisoJDialog(controlador);
		 	piso.setSuperficie(supTotal);
		 	piso.getContentPane().setVisible(false);
	    }

	@Test
	public void testCrearPisoJDialog() {
		
		try{
	    	piso.botonCrear();
	    	fail("El método debería de haber fallado");
    	}
    	catch(ParseException e){
    		assertTrue(true);
    	}
		/*try{
			superficie = Integer.parseInt(piso.getSuperficie_total());
			assertTrue("El número no es positivo", superficie>=0);
		}
		catch(NumberFormatException e){
			fail("Debes de introducir un valor numérico");
		}*/
		
	}

}
